
name: Solar System
on: 
    workflow_dispatch:
    push:
        branches:
            - main
            - 'feature/*'
env:
    MONGO_URL: 'mongodb+srv://supercluster.d83jj.mongodb.net/superData'
    MONGO_USERNAME: ${{ vars.username}}
    MONGO_PASSWORD: ${{secrets.passwrod}}   

jobs:            
    unit_testing:
        name: Unit Testing
        runs-on: ubuntu-latest
        steps:
            - name: Checkout
              uses: actions/checkout@v2

            - name: install node js
              uses: actions/setup-node@v4
              with: 
                node-version: 18

            - name : Install dependency
              run : npm install

            - name: run unite test
              run : npm test  