
name: Solar System
on: 
    workflow_dispatch:
    push:
        branches:
            - main
            - 'feature/*'
env:
    MONGO_URI: 'mongodb+srv://supercluster.d83jj.mongodb.net/superData'
    MONGO_USERNAME: ${{ vars.MONGO_USERNAME }}
    MONGO_PASSWORD: ${{ secrets.MONGO_PASSWORD }}   

jobs:            
    unit_testing:
        name: Unit Testing
        strategy:
          matrix:
            node_version: [18,19]
            operating_system: [ubuntu-latest]
            exclude:
              - node_version: 19
                operating_system: macos-latest

        runs-on: ${{matrix.operating_system}}
        steps:
            - name: Checkout
              uses: actions/checkout@v2

            - name: install node js
              uses: actions/setup-node@v4
              with: 
                node-version: ${{matrix.node_version}}

            - name : Install dependency
              run : npm install

            - name: run unit test
              id: test_id
              run : npm test  


            - name: Download test report
              if: steps.test_id.outcome ==success()
              uses : actions/upload-artifact@v4
              with:
                name: vinu-${{matrix.node_version}}-${{matrix.operating_system}}
                path: test-results.xml
    code_coverage:
        if: success()
        name: code coverage
        needs: unit_testing
        # strategy:
        #   matrix:
        #     node_version: [18,19,20]
        #     operating_system: [ubuntu-latest,macos-latest]
        #     exclude:
        #       - node_version: 19
        #         operating_system: macos-latest

        runs-on: ubuntu-latest  
        #${{matrix.operating_system}}
        steps:
            - name: Checkout
              uses: actions/checkout@v2

            - name: install node js
              uses: actions/setup-node@v4
              with: 
                node-version: 18
                #${{matrix.node_version}}

            - name : Install dependency
              run : npm install
                
            - name: check code coverage
              continue-on-error: true
              run : npm run coverage 


            - name: Download test report
              uses : actions/upload-artifact@v4
              with:
                name: vinucoverage
                #${{matrix.node_version}}-${{matrix.operating_system}}
                path: coverage
    docker_login:
      name: Docker Login
      needs: [unit_testing,code_coverage]
      runs-on: ubuntu-latest
      steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ vars.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}   
      
      - name: Login to github registry
        uses: docker/login-action@v3
        with:
            registry: ghcr.io
            username: ${{ github.repository_owner }}
            password: ${{ secrets.PAT}}        

      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          context: .
          push: true
          tags: |
           ${{ vars.DOCKERHUB_USERNAME }}/solar-${{github.sha}}  
           ghcr.io/${{ github.repository_owner }}/solar-${{github.sha}}    



      - name: Test Docker Image
        run: |
            docker images 
            docker run -d ${{ vars.DOCKERHUB_USERNAME  }}/solar-${{ github.sha }}
        
        