
name: Solar System
on: 
    workflow_dispatch:
    push:
        branches:
            - main
            - 'feature/*'
jobs:            
    unit_testing:
        name: Unit Testing
        runs-on: ubuntu-latest
        steps:
            - name: Checkout
              uses: actions/checkout@v2

            - name: install node js
              uses: actions/setup-node@v4
              with: 
                node-version: 18

            - name : Install dependency
              run : npm install

            - name: run unite test
              run : npm test  